add sshrc support for when bash is not explicitely set as default shell

diff --git a/bin/sshrc b/bin/sshrc
--- a/bin/sshrc
+++ b/bin/sshrc
@@ -56,6 +56,17 @@ EOF
 EOF
                 )"' | tr -s ' ' $'\n' | openssl enc -base64 -d > \$SSHHOME/bashsshrc
             chmod +x \$SSHHOME/bashsshrc
+            if test sh = \$(ps -p \$\$ | awk '\$1 != \"PID\" {print \$(NF)}'); then
+                echo >&2 \"sshrc requires a default shell different than sh\";
+                if command -v bash >/dev/null 2>&1; then
+                    export SSHHOME=\$SSHHOME
+                    echo \"$CMDARG\" >> \$SSHHOME/sshrc.bashrc
+                    bash --rcfile \$SSHHOME/sshrc.bashrc
+                else
+                    sh
+                fi
+                exit $?
+            fi
 
             echo $'"$(tar czf - -h -C $SSHHOME $files | openssl enc -base64)"' | tr -s ' ' $'\n' | openssl enc -base64 -d | tar mxzf - -C \$SSHHOME
             export SSHHOME=\$SSHHOME
@@ -94,8 +105,8 @@ function sshrc_parse() {
 
 sshrc_parse "$@"
 if [[ -z "${CMDARG// /}" ]]; then
-	command -v openssl >/dev/null 2>&1 || { echo >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting."; exit 1; }
-	sshrc
+    command -v openssl >/dev/null 2>&1 || { echo >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting."; exit 1; }
+    sshrc
 else
-	command ssh "$@"
+    command ssh "$@"
 fi
